table Medidas
	lineageTag: dbd831ca-be33-47c0-b00a-f77958e3ca9d

	measure 'Internet Total Sales Amount' =
			
			
			SUM(InternetSales[SalesAmount])
		formatString: "S/"\ #,0;-"S/"\ #,0;"S/"\ #,0
		displayFolder: Funciones de agregación
		lineageTag: 4dc01027-5fa1-4509-a884-82058f1bac34

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Maxima Venta por Internet' = ```
			
			
			MAX(InternetSales[SalesAmount])
			
			```
		formatString: "S/"\ #,0.###############;-"S/"\ #,0.###############;"S/"\ #,0.###############
		displayFolder: Funciones de agregación
		lineageTag: c9960167-778b-412a-9e47-e54dd353cb55

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Minima Venta por Internet' =
			
			MIN(InternetSales[SalesAmount])
		formatString: "S/"\ #,0.###############;-"S/"\ #,0.###############;"S/"\ #,0.###############
		displayFolder: Funciones de agregación
		lineageTag: 8d0f218b-0037-4d48-b8c2-a8e592a7c5a6

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Internet Total OrderQuantity' = SUM(InternetSales[OrderQuantity])
		displayFolder: Funciones de agregación
		lineageTag: 229d82ad-1a41-4d23-89db-a2f80467b75b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Internet Total Quantity Red Color' =
			
			SUMX(FILTER(InternetSales,RELATED('Product'[Color])="Red"),
			InternetSales[OrderQuantity])
		displayFolder: Funciones de iteración
		lineageTag: a1eee4a6-cb65-46f2-a4c8-3cb099ce7364

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cantidad de Clientes' =
			
			
			COUNT(Customer[CustomerKey])
		formatString: 0
		displayFolder: Funciones de agregación
		lineageTag: 997c2d9d-a82c-45fc-ae7c-e2192cf0aca4

	measure 'Cantidad de registros en Customers' =
			
			
			COUNTROWS(Customer)
		formatString: 0
		displayFolder: Funciones de agregación
		lineageTag: 6d7c3c98-dd4b-49a7-b0ad-1849057446ce

	measure 'Cantidad de Clientes Unicos' =
			
			
			DISTINCTCOUNT(Customer[CustomerKey])
		formatString: 0
		displayFolder: Funciones de agregación
		lineageTag: 2a717255-4d8c-4d62-9450-abce263cb8a0

	measure 'Internet Total Sales amount Category Bicicleta' =
			
			
			CALCULATE(Medidas[Internet Total Sales Amount],
			FILTER(ProductCategory,ProductCategory[SpanishProductCategoryName]= "Bicicleta"))
		formatString: "S/"\ #,0.###############;-"S/"\ #,0.###############;"S/"\ #,0.###############
		displayFolder: Funciones CALCULATE
		lineageTag: cc417a5c-9ad8-413f-8ab1-41db86d774f7

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure '% Participacion de categoria bicicleta' = ```
			
			
			
			var _total = [Internet Total Sales Amount]
			
			var _total_bicicleta = [Internet Total Sales amount Category Bicicleta]
			
			
			return
			
			DIVIDE(_total_bicicleta,_total,0)
			
			
			```
		displayFolder: Funciones con variables
		lineageTag: 6f876b37-9d6c-4b94-b6ab-92a1a09dcb42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Monto venta mes anterior' = CALCULATE([Internet Total Sales Amount],PREVIOUSMONTH(Calendario[Date]))
		formatString: "S/"\ #,0;-"S/"\ #,0;"S/"\ #,0
		displayFolder: Funciones de Inteligencia de Tiempo
		lineageTag: c9c8fe1a-59e0-423e-b6f2-cbadb02773be

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Monto venta mismo año anterior' =
			
			
			VAR _Total_Ventas=[Internet Total Sales Amount]
			
			VAR _Venta_anio_anterior = CALCULATE([Internet Total Sales Amount],SAMEPERIODLASTYEAR(Calendario[Date]))
			
			RETURN
			    IF(_Total_Ventas=BLANK()=BLANK(),_Venta_anio_anterior)
		formatString: "S/"\ #,0;-"S/"\ #,0;"S/"\ #,0
		displayFolder: Funciones de Inteligencia de Tiempo
		lineageTag: effd8174-2dd5-4b8f-8a6c-13a44ce09da4

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Monto venta acumulado año' = ```
			CALCULATE([Internet Total Sales Amount],DATESYTD(Calendario[Date]))
			
			
			
			
			```
		formatString: "S/"\ #,0;-"S/"\ #,0;"S/"\ #,0
		displayFolder: Funciones de Inteligencia de Tiempo
		lineageTag: e9dc776a-2eb5-4bd2-b22d-6934b8762122

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Monto venta acumulado año FY' = CALCULATE([Internet Total Sales Amount],DATESYTD(Calendario[Date],"06/30"))
		formatString: "S/"\ #,0;-"S/"\ #,0;"S/"\ #,0
		displayFolder: Funciones de Inteligencia de Tiempo
		lineageTag: cadd9896-deaf-40ee-ba7c-ba3931c406c9

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Monto venta acumulado por Quarter' =
			
			
			CALCULATE([Internet Total Sales Amount],DATESQTD(Calendario[Date]))
		formatString: "S/"\ #,0;-"S/"\ #,0;"S/"\ #,0
		displayFolder: Funciones de Inteligencia de Tiempo
		lineageTag: 7a33d268-c300-4219-9b39-bab299972210

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Monto venta mes anterior DATEADD' =
			
			
			CALCULATE([Internet Total Sales Amount],DATEADD(Calendario[Date],-1,MONTH))
		formatString: "S/"\ #,0;-"S/"\ #,0;"S/"\ #,0
		displayFolder: Funciones de Inteligencia de Tiempo
		lineageTag: 843192bc-e60b-47fc-a33f-4289af9b8864

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Monto Vta fecha envio' = ```
			
			
			CALCULATE([Internet Total Sales Amount],USERELATIONSHIP(OrderDate[DateKey],InternetSales[ShipDateKey]))
			
			
			```
		formatString: 0
		lineageTag: 28fdce79-df51-4188-aeec-1a931219718c

	partition Medidas = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

